from enum import Enum

class ErrorType(Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_ROUTE = "INVALID_ROUTE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    
    # Dataset errors
    INVALID_DATASET = "INVALID_DATASET"
    EMPTY_DATASET_DIR = "EMPTY_DATASET_DIR"